version: '3.8'
networks:
    db:
        driver: 'bridge'
services:
    server:
        restart: 'always'
        build:
            dockerfile: 'docker/php8.0-xdebug-composer-node16.Dockerfile'
        container_name: 'budget-server'
        environment:
            - 'TZ=America/Toronto'
        volumes:
            -   type: 'bind'
                source: '.'
                target: '/var/www/html/'
            -   type: 'bind'
                source: 'docker/certs'
                target: '/etc/ssl/certs/'
            -   type: 'bind'
                source: 'docker/virtual-hosts.conf'
                target: '/etc/apache2/sites-available/000-default.conf'
        ports:
            -   mode: 'host'
                published: 3280
                target: 80
                protocol: 'tcp'
            -   mode: 'host'
                published: 3281
                target: 443
                protocol: 'tcp'
            -   mode: 'host'
                published: 3282
                target: 3282
                protocol: 'tcp'
            -   mode: 'host'
                published: 3283
                target: 3283
                protocol: 'tcp'
        networks:
            - 'db'
    phpmyadmin:
        restart: 'always'
        image: 'phpmyadmin/phpmyadmin:5.0.1'
        container_name: 'budget-phpmyadmin'
        networks:
            - 'db'
        ports:
            -   mode: 'host'
                published: 3284
                target: 80
                protocol: 'tcp'
        environment:
            - 'PMA_HOSTS=budget-mysql'
#            - 'PMA_CONTROLPORT=3366'
            - 'PMA_USER=root'
            - 'UPLOAD_LIMIT=8192M'
            - 'MEMORY_LIMIT=8192M'
            - 'MAX_EXECUTION_TIME=10000'
            - 'MAX_INPUT_TIME=1000'
    mysql:
        restart: 'always'
        image: 'mariadb:10.3.35'
        container_name: 'budget-mysql'
        command: '--max_allowed_packet=32505856 '
        environment:
            - 'MYSQL_ROOT_PASSWORD:""'
            - 'MYSQL_ALLOW_EMPTY_PASSWORD=1'
            - 'MYSQL_DATABASE=budget-db'
        networks:
            - 'db'
        ports:
            -   mode: 'host'
                published: 3285
                target: 3306
                protocol: 'tcp'
        volumes:
            -   type: 'bind'
                source: mysql_files
                target: '/var/lib/mysql'
volumes:
    database_vol:
        name: budget-database
